name: OneTest Server Action

on: workflow_dispatch

jobs:

  OTS-Action:
    runs-on: test1
    name: Execute OTS Test
    steps:
      - name: Execute test
        uses: rathorpraveen/buildtestpraveen@main
        with:
          serverUrl: https://master-hcl.tp-k8s.nonprod.hclpnp.com/
          offlineToken: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJkNzMwNGM5MS0xMDJkLTRkYzEtOWRkYi1hYTcwZjc1ZDBiYmQifQ.eyJpYXQiOjE2NDg1NDgxNDQsImp0aSI6ImNmZWQ2ZjM1LTczOTUtNDkyNS05Zjc5LTZiZmU4YmIxMDc3ZCIsImlzcyI6Imh0dHBzOi8vbWFzdGVyLWhjbC50cC1rOHMubm9ucHJvZC5oY2xwbnAuY29tL2F1dGgvcmVhbG1zL3Rlc3RzZXJ2ZXIiLCJhdWQiOiJodHRwczovL21hc3Rlci1oY2wudHAtazhzLm5vbnByb2QuaGNscG5wLmNvbS9hdXRoL3JlYWxtcy90ZXN0c2VydmVyIiwic3ViIjoiY2VlMjk5MDgtNmQxNi00OTg0LWFmNjEtYTE5Y2Y1ZjgyY2JkIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6InRlc3RzZXJ2ZXIiLCJzZXNzaW9uX3N0YXRlIjoiOWZkNjdiNTYtYjRmMC00ZDI3LTliZGItYjFmNTY0NGYyZDYwIiwic2NvcGUiOiJ0ZXN0c2VydmVyIGVtYWlsIG9mZmxpbmVfYWNjZXNzIHByb2ZpbGUifQ.lU0rnmuVRuj2JSLO2vHe_Z-72ovE8OIHT15sgR9yBBU
          teamspace: Initial Team Space
          project: demo
          branch: Swadesh_Common_FTProject
          repository: git@github01.hclpnp.com:testingproducts/FT_SVT_TestAsset.git
          filepath: RITProject1013/Logical/calculator.wsc/Add.opr/AddTest.tsq
          environment: COMP-4518-1
